name: Task 1 - Fix the broken workflow

on: [push]

jobs:
  task1:
    name: Task 1 - Fix the broken workflow
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Checkout
        uses: actions/checkout@v3
      defaults:
        run:
          working-directory: example-app
      - run: npm install
      - run: npm run lint
      - run: npx playwright install
      - run: npm test
      - run: npm run build
