name: Task 2 - Optimizing the workflow

concurrency:
  cancel-in-progress: true
  group: roger

defaults:
  run:
    working-directory: ./example-app

on: [push]

jobs:
  job1:
    name: Task 1 - Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Checkout
        uses: actions/checkout@v3
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/checkout@v3
      - name: Lint
        run: npm install && npm run lint
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/checkout@v3
      - name: Test
        run: npm install && npx playwright install && npm test
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/checkout@v3
      - name: Run
        run: npm install && npm run build

